---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
  namespace: fabric
  # For IBM File Storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-silver"
  labels:
    billingType: "hourly"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 19Gi
  selector:
    matchLabels:
      name: sharedvolume

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
  namespace: org1
  # For IBM File Storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-silver"
  labels:
    billingType: "hourly"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 19Gi
  selector:
    matchLabels:
      name: shared-org1

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
  namespace: org2
  # For IBM File Storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-silver"
  labels:
    billingType: "hourly"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 19Gi
  selector:
    matchLabels:
      name: shared-org2

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
  namespace: ordererorg1
  # For IBM File Storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-silver"
  labels:
    billingType: "hourly"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 19Gi
  selector:
    matchLabels:
      name: shared-ordererorg1

