---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared-pv
  labels:
    name: sharedvolume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  # change nfs server & path
  nfs:
   server: "fsf-seo0101a-fz.adn.networklayer.com"
   path: "/IBM02SEV1557043_64/data01"
#  hostPath:
#    path: "/tmp/fabric"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared-org1
  labels:
    name: shared-org1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
   server: "fsf-seo0101a-fz.adn.networklayer.com"
   path: "/IBM02SEV1557043_64/data01"
#  hostPath:
#    path: "/tmp/fabric"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared-org2
  labels:
    name: shared-org2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
   server: "fsf-seo0101a-fz.adn.networklayer.com"
   path: "/IBM02SEV1557043_64/data01"
#  hostPath:
#    path: "/tmp/fabric"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared-ordererorg1
  labels:
    name: shared-ordererorg1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
   server: "fsf-seo0101a-fz.adn.networklayer.com"
   path: "/IBM02SEV1557043_64/data01"
#  hostPath:
#    path: "/tmp/fabric"
